### PR TITLE
Require IRB explicitly

### PR DESCRIPTION
**Pull request by genya0407**
Solution for https://github.com/mrkn/iruby-rails/issues/1 .

### CODE REVIEW

**Comment by mrkn** [comment]
@genya0407 Thanks for making this PR.

I have one question.  I’m concerned that irb is required unconditionally.  Is this requirement necessary if IRuby uses pry instead of irb?

**Comment by genya0407** [comment]
If Rails app is configured to use pry as console, we don't have to require irb.

So, it's better to require irb conditionally.
I'll modify later.

**Comment by mrkn** [comment]
@genya0407 I found that console helpers such as `app`, `controller`, and `helper` aren't worked well.
Can you investigate the reason why these commands are not available?

In `rails console` command, they are available like this:

```console
$ be rails console
Running via Spring preloader in process 63785
Loading development environment (Rails 5.1.1)
irb(main):001:0> helper
=> #<ActionView::Base:0x007fbad9c185e0 @_config={}, @view_renderer=#<ActionView::Renderer:0x007fbad9c12e88 @lookup_context=#<ActionView::LookupContext:0x007fbad9c132c0 @details_key=nil, @cache=true, @prefixes=[], @rendered_format=nil, @details={:locale=>[:en], :formats=>[:html, :text, :js, :css, :ics, :csv, :vcf, :png, :jpeg, :gif, :bmp, :tiff, :svg, :mpeg, :xml, :rss, :atom, :yaml, :multipart_form, :url_encoded_form, :json, :pdf, :zip, :gzip], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee, :jbuilder]}, @view_paths=#<ActionView::PathSet:0x007fbad9c12ed8 @paths=[]>>>, @_assigns={}, @_controller=nil, @view_flow=#<ActionView::OutputFlow:0x007fbad9c03d70 @content={}>, @output_buffer=nil, @virtual_path=nil>
irb(main):002:0> controller
=> #<ApplicationController:0x007fbad9c004e0 @_action_has_layout=true, @_routes=nil, @_request=nil, @_response=nil>
irb(main):003:0> app
=> #<ActionDispatch::Integration::Session:0x007fbad450c3c8 @_routes=nil, @app=#<TestApp::Application:0x007fbad7859280 @_all_autoload_paths=["/private/tmp/test_app/app/assets", "/private/tmp/test_app/app/channels", "/private/tmp/test_app/app/controllers", "/private/tmp/test_app/app/controllers/concerns", "/private/tmp/test_app/app/helpers", "/private/tmp/test_app/app/jobs", "/private/tmp/test_app/app/mailers", "/private/tmp/test_app/app/models", "/private/tmp/test_app/app/
```

The following lines should activate these commands if my memory is exact:
https://github.com/mrkn/iruby-rails/blob/master/lib/iruby/rails.rb#L42-L44

**Comment by genya0407** [comment]
@mrkn Sure. I'll work on it.

**Pull request closed without merging**
